version: "3.8"
services:
  goauth-db:
    image: postgres:14.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "goauth-db"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
